<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Leader_on_duty_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->leader_on_duty_id	= 'ID';
		$this->leader_on_duty_agentid	= 'AGENTID';
		$this->leader_on_duty_tanggal	= 'TANGGAL';
		$this->leader_on_duty_gelombang	= 'GELOMBANG';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_agentid	= 'agentid';
		$this->f_tanggal	= 'tanggal';
		$this->f_gelombang	= 'gelombang';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->leader_on_duty_id,
			$this->f_agentid	=> $this->leader_on_duty_agentid,
			$this->f_tanggal	=> $this->leader_on_duty_tanggal,
			$this->f_gelombang	=> $this->leader_on_duty_gelombang,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-31 15:28:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

