<?php
require APPPATH . '/controllers/Histori_call/Histori_call_config.php';

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Histori_call extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('Custom_model/Dapros_model', 'tmodel');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Trans_helpdesk_model', 'trans_helpdesk');
		$this->load->model('Custom_model/T_handle_time_model', 'T_handle_time_model');
		$this->log_key = 'log_Indibox';
		$this->title = new Histori_call_config();
	}


	function index()
	{
		$post = $this->input->get();
		$idlogin = $this->session->userdata('idlogin');
		$logindata = $this->log_login->get_by_id($idlogin);
		$userdata = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));
		$data['userdata'] = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));
		$no = 0;

		$data['data'] = $this->get_by_date($post);
		$data['post'] = $post;
		$this->template->load('Histori_call/List', $data);
	}
	function get_by_date($post)
	{
		$filter = "";
		$start = date('Y-m-d');
		$end = date('Y-m-d');
		$filter = " AND DATE(lup) >='$start' AND DATE(lup) <='$end' ";
		if (isset($post['filter'])) {
			if ($post['filter'] == 'periode') {
				if (isset($post['start'])) {
					$start = $post['start'];
					$end = $post['end'];
				}
				$filter = " AND DATE(lup) >='$start' AND DATE(lup) <='$end' ";
			} else {
				$keyword = $post['keyword'];
				$filter = " AND (NDEM LIKE '%$keyword%' OR ND_SPEEDY LIKE '%$keyword%' OR  EXTERNAL_ORDER_ID LIKE '%$keyword%')";
			}
		}
		$data['list_outbound'] = $this->tmodel->live_query("SELECT *,status as v_status from dapros_helpdesk_va WHERE status > 0 $filter ")->result();
		return $data;
	}
};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-06-02 15:25:04 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
